baseURL = "https://gerstle.org/"
languageCode = "en-us"
title = "Gerstle"
theme = "darksimplicity"
copyright = "<!-- Copyright 2017 --> "

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true


[params]
#google_analytics_id=""


[menu]
  [[menu.top]]
  name = "RSS"
  pre = ""
  weight = -90
  url = "index.xml"
